### PR TITLE
chore(all): Add clang-format and format repository

### PR DESCRIPTION
**Pull request by sam-mathews**
This commit ensures a consistent code style across the repository.

### CODE REVIEW

**Review by LuminousSpike — CHANGES_REQUESTED** [review]
Can you adjust this to target develop instead of main please? Other than that, it looks good to me.

**Comment by sam-mathews** [comment]
What's the point of a develop branch in this instance?

**Comment by LuminousSpike** [comment]
Every commit to main creates a new release automatically via the pipeline. Merging first to develop allows us to batch our changes and produce a new release when we have more features implemented.

**Comment by sam-mathews** [comment]
I feel like restricting release builds to tags would make a lot more sense, but I can target develop.

**Comment by LuminousSpike** [comment]
> I feel like restricting release builds to tags would make a lot more sense, but I can target develop.

Good idea, I'll create a Github issue to track that.

**Review by LuminousSpike — APPROVED** [review]
Since the changes to the workflow have been implemented, this is all good to be merged in now once the conflicts are resolved.

**Pull request merged**
